# Generated by Django 4.0.4 on 2022-05-20 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('expects', 'Ожидает'), ('rejected', 'Отклонен'), ('accepted', 'Принят')], default='expects', max_length=11),
        ),
        migrations.CreateModel(
            name='LikedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedArticle', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedArticle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
