# Generated by Django 4.0.4 on 2022-05-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.ImageField(default=21, upload_to='image'),
            preserve_default=False,
        ),
    ]
