# Generated by Django 4.0.4 on 2022-05-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shortDescription',
            field=models.CharField(default='Краткое описание', max_length=500),
        ),
    ]
