# Generated by Django 4.0.4 on 2022-05-05 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_article_shortdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='shortDescription',
            field=models.TextField(default='Краткое описание', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default='Заголовок статьи', max_length=250),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Текст комментария', max_length=500)),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('expects', 'Ожидает'), ('rejected', 'Отклонен')], default='expects', max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
