# Generated by Django 4.0.4 on 2022-05-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_shortdescription_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('expects', 'Ожидает'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='expects', max_length=10),
        ),
    ]
