# Generated by Django 4.0.4 on 2022-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('rejected', 'Отклонен'), ('expects', 'Ожидает'), ('accepted', 'Принят')], default='expects', max_length=10),
        ),
    ]
