# Generated by Django 4.0.4 on 2022-05-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_content_alter_comment_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('expects', 'Ожидает'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='expects', max_length=10),
        ),
    ]
