# Generated by Django 4.0.4 on 2022-05-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('rejected', 'Отклонен'), ('expects', 'Ожидает')], default='expects', max_length=10),
        ),
    ]
