# Generated by Django 4.0.4 on 2022-05-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('rejected', 'Отклонен'), ('expects', 'Ожидает'), ('accepted', 'Принят')], default='expects', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='confirmationCode',
            field=models.IntegerField(),
        ),
    ]
