# Generated by Django 4.0.4 on 2022-05-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('expects', 'Ожидает'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='expects', max_length=10),
        ),
    ]
